dist: trusty
sudo: required

services:
    - docker

env:
    global:
        - DOCKER_DIR="$HOME/.cache/docker"
        - secure: "HhT1TdJcpqys8juVMw/DIZeK7oD4595TEKH5KlowH7MvwwFAUyQFb5W63F8dgk7elvRG+3fmga/m1JfXO+Iu7PVD912eiNDagW9aB3CEl3Z8zg+JUL8IjpMCkyKQDyJMnfOkrzdxdaqfOK+WmF+13f2qBu9Kc7wdXuzgHQrg4+0=" # CI_REGISTRY_USER
        - secure: "hh7VDZnkxgl/vqHtS4IpXfIAckKpVQvoCzNW7fstr5Mcu8KNiCWIPgObBRm+m13aqpcFTMWQ6lT2kzORz2wWRbDeVhI1eGWOJswGNHPHZLO0Jaei6yfY2nY2mpxZbl+vdg00jkN64mi1ab3e++QgeLFruW0gyNefXX7E5L/mHTs=" # CI_REGISTRY_PASS

cache:
    directories:
        - $DOCKER_DIR

before_install:
    - sudo apt-get update
    - sudo apt-get -y install docker-ce realpath
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASS

install: true

script:
    - test -f "$DOCKER_DIR/image.tar" && docker load -i "$DOCKER_DIR/image.tar" || true
    - docker build -t core:build --target build .
    - docker build -t core:dist --target dist --build-arg VCS_BRANCH="$TRAVIS_BRANCH" --build-arg VCS_COMMIT="$TRAVIS_COMMIT" .
    - docker build -t core:dev --target dev .
    - docker save -o "$DOCKER_DIR/image.tar" $(docker history -q core:build | grep -v '<missing>') $(docker history -q core:dist | grep -v '<missing>')
    - ./tests/bin/docker-tests.sh --image core:dev

after_success:
    - if [ "$TRAVIS_TAG" ]; then
          docker tag core:dist scitran/core:$TRAVIS_TAG;
          docker push scitran/core:$TRAVIS_TAG;
      fi
    - if [ "$TRAVIS_EVENT_TYPE" == "push" -a "$TRAVIS_BRANCH" == "nginx-unit" ]; then
          docker tag core:dev scitran/core:nginx-unit;
          docker push scitran/core:nginx-unit;
      fi
