sudo: required
dist: trusty

install:
  - test/bin/install-docker-travis.sh
  - pip install -U coveralls

script:
  - test/bin/run-tests-docker.sh -b

after_success:
  - sed -i "s|/var/scitran/code/api|`pwd`|g" .coverage # hack to make line coverage work for coverage.py
  - coveralls
