#Travis OSX currently doesn't not support docker (via virtualbox).
# "This computer doesn't have VT-X/AMD-v enabled."
sudo: required
dist: trusty
services:
  - mongodb
install:
  - bin/install-ubuntu.sh
  - test/bin/setup-integration-tests-ubuntu.sh
script:
  - SCITRAN_PERSISTENT_DB_PORT=27017 test/bin/run-tests-ubuntu.sh
after_success:
  - coveralls
